version: '3.3'
services:
  web:
    image: entrega_1:latest
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "81:80"
    links:
      - localhost
    volumes:
      - ./app:/var/www/html/

  localhost:
    image: mariadb:10.8.2
    restart: always
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: login_register_db
    ports:
      - "8889:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - localhost
    ports:
      - 8890:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: login_register_db
